  
name: Bicep build
on: push

jobs:
  build_and_test:
    name: Build and Test

    runs-on: windows-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Run the private action
      uses: ./
      with:
        files: 'test/onefile.bicep test/anotherfile.bicep test/samples/sampleonfolder.bicep'

    - name: Check the result
      shell: bash
      run: |
        ls test/
        ls test/samples/